# Generated by Django 3.1.5 on 2021-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ManyToManyField(to='apps.Category'),
        ),
    ]
