# Generated by Django 3.1.5 on 2021-02-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210204_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='app',
            new_name='post',
        ),
    ]
